<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QPDABEC" ignored="0" name="failcheck" tests="11" failures="1" timestamp="22 Jun 2020 18:27:54 GMT" time="0.102" errors="0">
  <testcase name="testA" time="0.007" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.002" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.002" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.002" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.004" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.0" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.002" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.003" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.002" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.0" classname="org.base.test.FailCheck">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.0" classname="org.base.test.FailCheck">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at org.base.test.FailCheck.testA(FailCheck.java:16)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
</testsuite> <!-- failcheck -->
